import { cuisines, dishes } from "./food/data.ts";
import { SITE_URL } from "./site.ts";

/**
 * Pages worth indexing. Checkout, order and saved pages are personal or
 * transactional and left out on purpose.
 */
export const STATIC_PATHS = ["/", "/menu", "/ingredients", "/delivery"] as const;

export function sitemapPaths(): string[] {
  return [
    ...STATIC_PATHS,
    ...cuisines.map((c) => `/menu/${c.id}`),
    ...dishes.map((d) => `/dish/${d.id}`),
  ];
}

/** public/sitemap.xml, generated by `npm run sitemap`. */
export function sitemapXml(): string {
  const urls = sitemapPaths()
    .map((path) => `  <url><loc>${new URL(path, SITE_URL).toString()}</loc></url>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}
