/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as KitchensRouteImport } from './routes/kitchens'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as DishIdRouteImport } from './routes/dish.$id'
import { Route as MenuCuisineRouteImport } from './routes/menu.$cuisine'
import { Route as OrderIdRouteImport } from './routes/order.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchensRoute = KitchensRouteImport.update({
  id: '/kitchens',
  path: '/kitchens',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const DishIdRoute = DishIdRouteImport.update({
  id: '/dish/$id',
  path: '/dish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuCuisineRoute = MenuCuisineRouteImport.update({
  id: '/$cuisine',
  path: '/$cuisine',
  getParentRoute: () => MenuRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/ingredients': typeof IngredientsRoute
  '/kitchens': typeof KitchensRoute
  '/menu': typeof MenuRouteWithChildren
  '/partners': typeof PartnersRoute
  '/trace': typeof TraceRoute
  '/dish/$id': typeof DishIdRoute
  '/menu/$cuisine': typeof MenuCuisineRoute
  '/order/$id': typeof OrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/ingredients': typeof IngredientsRoute
  '/kitchens': typeof KitchensRoute
  '/menu': typeof MenuRouteWithChildren
  '/partners': typeof PartnersRoute
  '/trace': typeof TraceRoute
  '/dish/$id': typeof DishIdRoute
  '/menu/$cuisine': typeof MenuCuisineRoute
  '/order/$id': typeof OrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/ingredients': typeof IngredientsRoute
  '/kitchens': typeof KitchensRoute
  '/menu': typeof MenuRouteWithChildren
  '/partners': typeof PartnersRoute
  '/trace': typeof TraceRoute
  '/dish/$id': typeof DishIdRoute
  '/menu/$cuisine': typeof MenuCuisineRoute
  '/order/$id': typeof OrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/delivery'
    | '/ingredients'
    | '/kitchens'
    | '/menu'
    | '/partners'
    | '/trace'
    | '/dish/$id'
    | '/menu/$cuisine'
    | '/order/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/delivery'
    | '/ingredients'
    | '/kitchens'
    | '/menu'
    | '/partners'
    | '/trace'
    | '/dish/$id'
    | '/menu/$cuisine'
    | '/order/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/delivery'
    | '/ingredients'
    | '/kitchens'
    | '/menu'
    | '/partners'
    | '/trace'
    | '/dish/$id'
    | '/menu/$cuisine'
    | '/order/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  IngredientsRoute: typeof IngredientsRoute
  KitchensRoute: typeof KitchensRoute
  MenuRoute: typeof MenuRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  TraceRoute: typeof TraceRoute
  DishIdRoute: typeof DishIdRoute
  OrderIdRoute: typeof OrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchens': {
      id: '/kitchens'
      path: '/kitchens'
      fullPath: '/kitchens'
      preLoaderRoute: typeof KitchensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$id': {
      id: '/dish/$id'
      path: '/dish/$id'
      fullPath: '/dish/$id'
      preLoaderRoute: typeof DishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$cuisine': {
      id: '/menu/$cuisine'
      path: '/$cuisine'
      fullPath: '/menu/$cuisine'
      preLoaderRoute: typeof MenuCuisineRouteImport
      parentRoute: typeof MenuRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenuRouteChildren {
  MenuCuisineRoute: typeof MenuCuisineRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuCuisineRoute: MenuCuisineRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  IngredientsRoute: IngredientsRoute,
  KitchensRoute: KitchensRoute,
  MenuRoute: MenuRouteWithChildren,
  PartnersRoute: PartnersRoute,
  TraceRoute: TraceRoute,
  DishIdRoute: DishIdRoute,
  OrderIdRoute: OrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
