import type { DishRecord } from "./types.ts";
import { generated, representative } from "./images.ts";

export const dishRecords: DishRecord[] = [
  // ─── India ────────────────────────────────────────────────────────────────
  {
    id: "butter-chicken",
    cuisine: "india",
    name: "Butter Chicken",
    localName: "मुर्ग़ मखनी",
    tradition: "Punjabi",
    course: "main",
    story:
      "Developed in Delhi's Punjabi restaurant kitchens after 1947, when cooks simmered tandoori chicken in a buttery tomato gravy. The chicken is marinated in yogurt and spices, charred, then finished in a sauce of tomato, butter, cream and dried fenugreek.",
    parts: [
      {
        label: "Chicken",
        items: [
          "Chicken thigh",
          "Yogurt",
          "Lemon juice",
          "Ginger",
          "Garlic",
          "Kashmiri chili (mild, deep-red dried chili)",
          "Salt",
        ],
      },
      {
        label: "Makhani sauce",
        items: [
          "Tomato",
          "Butter",
          "Cream",
          "Cashew",
          "Ginger",
          "Garlic",
          "Green chili",
          "Kashmiri chili",
          "Kasuri methi (dried fenugreek leaves)",
          "Sugar",
          "Salt",
        ],
      },
      {
        label: "Garam masala",
        items: [
          "Cumin",
          "Coriander seed",
          "Green cardamom",
          "Black cardamom",
          "Cinnamon",
          "Clove",
          "Black pepper",
          "Bay leaf",
          "Mace",
        ],
      },
    ],
    cookedIn: ["Butter"],
    allergens: ["milk", "tree-nuts"],
    diet: ["gluten-free"],
    spice: 1,
    price: 1490,
    image: representative(
      "/food/butter-chicken.jpg",
      "Butter chicken in a dark pan, orange tomato gravy drizzled with cream and scattered with herbs",
      "50% 55%",
    ),
    featured: true,
  },
  {
    id: "chicken-biryani",
    cuisine: "india",
    name: "Hyderabadi Biryani",
    localName: "حیدرآبادی بریانی",
    tradition: "Hyderabadi",
    course: "rice",
    story:
      "A biryani associated with the kitchens of Hyderabad's Nizams. Raw marinated chicken and part-cooked basmati are layered in a sealed pot and slow-cooked on dum (low, trapped heat), so the rice steams in the meat's juices with saffron, fried onion and mint.",
    parts: [
      {
        label: "Chicken marinade",
        items: [
          "Chicken (bone-in)",
          "Yogurt",
          "Ginger",
          "Garlic",
          "Green chili",
          "Red chili powder",
          "Turmeric",
          "Lemon juice",
          "Mint",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Biryani masala",
        items: [
          "Green cardamom",
          "Black cardamom",
          "Cinnamon",
          "Clove",
          "Shahi jeera (black cumin)",
          "Black pepper",
          "Mace",
          "Nutmeg",
          "Bay leaf",
        ],
      },
      {
        label: "Rice",
        items: ["Basmati rice", "Bay leaf", "Green cardamom", "Clove", "Shahi jeera", "Salt"],
      },
      {
        label: "Layering",
        items: [
          "Saffron",
          "Milk",
          "Ghee",
          "Fried onion (birista)",
          "Mint",
          "Cilantro",
          "Kewra water (screwpine flower water)",
        ],
      },
      {
        label: "Raita",
        items: ["Yogurt", "Cucumber", "Onion", "Mint", "Roasted cumin", "Salt"],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 2,
    price: 1550,
    image: representative(
      "/food/chicken-biryani.jpg",
      "Chicken biryani in a dark pot, topped with fried onion and mint, with a bowl of raita beside it",
      "50% 50%",
    ),
    featured: true,
  },
  {
    id: "masala-dosa",
    cuisine: "india",
    name: "Masala Dosa",
    localName: "ಮಸಾಲ ದೋಸೆ",
    tradition: "South Indian",
    course: "main",
    story:
      "A South Indian crepe of fermented rice and urad dal batter, spread thin on a hot griddle until crisp and folded around spiced potato. The filled version is often traced to Udupi cooks in Karnataka.",
    parts: [
      {
        label: "Dosa batter",
        items: ["Rice", "Urad dal (split black gram)", "Fenugreek seed", "Salt"],
      },
      {
        label: "Potato masala",
        items: [
          "Potato",
          "Onion",
          "Green chili",
          "Ginger",
          "Curry leaves",
          "Mustard seed",
          "Urad dal",
          "Chana dal (split chickpeas)",
          "Turmeric",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Coconut chutney",
        items: [
          "Coconut",
          "Roasted chana dal",
          "Green chili",
          "Ginger",
          "Mustard seed",
          "Curry leaves",
          "Dried red chili",
          "Salt",
        ],
      },
      {
        label: "Sambar",
        items: [
          "Toor dal (split pigeon peas)",
          "Tamarind",
          "Tomato",
          "Shallot",
          "Drumstick (moringa pod)",
          "Turmeric",
          "Mustard seed",
          "Curry leaves",
          "Asafoetida (pure dried resin, no flour added)",
          "Salt",
        ],
      },
      {
        label: "Sambar powder",
        items: [
          "Coriander seed",
          "Dried red chili",
          "Chana dal",
          "Urad dal",
          "Fenugreek seed",
          "Cumin",
          "Black pepper",
          "Curry leaves",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["vegetarian", "vegan", "gluten-free"],
    spice: 1,
    price: 1290,
    image: representative(
      "/food/masala-dosa.jpg",
      "Crisp rolled masala dosa with yellow potato filling, with bowls of coconut chutney and sambar",
      "50% 50%",
    ),
    featured: true,
  },
  {
    id: "palak-paneer",
    cuisine: "india",
    name: "Palak Paneer",
    localName: "पालक पनीर",
    tradition: "Punjabi",
    course: "main",
    story:
      "A North Indian dish in which cubes of paneer, an unaged cheese made by curdling milk with acid, are simmered in a purée of blanched spinach cooked with onion, tomato, ginger, garlic and spices.",
    parts: [
      {
        label: "Paneer",
        items: ["Whole milk", "Lemon juice"],
      },
      {
        label: "Spinach gravy",
        items: [
          "Spinach",
          "Onion",
          "Tomato",
          "Ginger",
          "Garlic",
          "Green chili",
          "Cream",
          "Kasuri methi (dried fenugreek leaves)",
          "Salt",
        ],
      },
      {
        label: "Spices",
        items: [
          "Cumin seed",
          "Coriander seed",
          "Turmeric",
          "Kashmiri chili (mild, deep-red dried chili)",
          "Green cardamom",
          "Cinnamon",
          "Clove",
          "Black pepper",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 1,
    price: 1350,
    image: generated(
      "/food/palak-paneer-ai.jpg",
      "Palak paneer: cubes of paneer in a dark green spinach gravy, in a ceramic bowl, with naan behind",
      { focal: "45% 55%", note: "The naan behind the bowl isn't part of this dish." },
    ),
  },
  {
    id: "tikka-masala",
    cuisine: "india",
    name: "Chicken Tikka Masala",
    localName: "चिकन टिक्का मसाला",
    tradition: "British Asian",
    course: "main",
    story:
      "Developed in British curry houses run by South Asian cooks in the later 20th century; its exact origin is disputed. Yogurt-marinated chicken tikka is grilled, then simmered in a spiced tomato and onion sauce finished with cream.",
    parts: [
      {
        label: "Chicken tikka",
        items: [
          "Chicken thigh",
          "Yogurt",
          "Lemon juice",
          "Ginger",
          "Garlic",
          "Kashmiri chili (mild, deep-red dried chili)",
          "Cumin",
          "Coriander seed",
          "Salt",
        ],
      },
      {
        label: "Masala sauce",
        items: [
          "Onion",
          "Tomato",
          "Ginger",
          "Garlic",
          "Green chili",
          "Cream",
          "Kasuri methi (dried fenugreek leaves)",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Spice blend",
        items: [
          "Cumin",
          "Coriander seed",
          "Turmeric",
          "Kashmiri chili",
          "Green cardamom",
          "Cinnamon",
          "Clove",
          "Black pepper",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 2,
    price: 1490,
    // The old photo showed a dark brown curry, not the orange, cream-finished
    // tikka masala on this menu (the same scene was also used for another dish).
    image: generated(
      "/food/tikka-masala-ai.jpg",
      "Chicken tikka masala: charred chicken pieces in an orange cream sauce with cilantro, naan behind the bowl",
      { focal: "50% 55%", note: "The naan behind the bowl isn't part of this dish." },
    ),
  },
  {
    id: "tandoori-chicken",
    cuisine: "india",
    name: "Tandoori Chicken",
    localName: "तंदूरी चिकन",
    tradition: "Punjabi",
    course: "main",
    story:
      "Popularized by Punjabi restaurateurs who moved from Peshawar to Delhi after Partition in 1947. Bone-in chicken is marinated first in lemon and chili, then in spiced yogurt, and traditionally roasted on skewers in a clay tandoor.",
    parts: [
      {
        label: "Chicken",
        items: [
          "Bone-in chicken legs",
          "Lemon juice",
          "Hung yogurt (strained yogurt)",
          "Ginger",
          "Garlic",
          "Butter (for basting)",
          "Salt",
        ],
      },
      {
        label: "Tandoori masala",
        items: [
          "Kashmiri chili (mild, deep-red dried chili)",
          "Cumin",
          "Coriander seed",
          "Black pepper",
          "Green cardamom",
          "Black cardamom",
          "Clove",
          "Cinnamon",
          "Mace",
          "Dried ginger",
          "Kasuri methi (dried fenugreek leaves)",
        ],
      },
      {
        label: "Mint chutney",
        items: [
          "Mint",
          "Cilantro",
          "Green chili",
          "Yogurt",
          "Lemon juice",
          "Roasted cumin",
          "Salt",
        ],
      },
      {
        label: "To serve",
        items: ["Red onion", "Lemon", "Cilantro"],
      },
    ],
    cookedIn: ["Butter"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 2,
    price: 1590,
    // The old photo showed boneless chicken skewers on a charcoal grill, not
    // bone-in tandoori chicken from a tandoor.
    image: generated(
      "/food/tandoori-chicken-ai.jpg",
      "Tandoori chicken: two charred, deep red bone-in chicken legs with sliced red onion and lemon wedges",
      { focal: "60% 50%" },
    ),
  },
  {
    id: "dal-makhani",
    cuisine: "india",
    name: "Dal Makhani",
    localName: "दाल मखनी",
    tradition: "Punjabi",
    course: "main",
    story:
      "Whole black urad and red kidney beans are simmered for hours until creamy, then finished with a tomato masala, butter and cream. The restaurant version took shape in Punjabi kitchens in Delhi after 1947.",
    parts: [
      {
        label: "Lentils",
        items: ["Whole urad (black gram)", "Rajma (red kidney beans)", "Ginger", "Salt"],
      },
      {
        label: "Masala",
        items: [
          "Onion",
          "Tomato",
          "Ginger",
          "Garlic",
          "Green chili",
          "Kashmiri chili (mild, deep-red dried chili)",
          "Cumin seed",
          "Butter",
          "Cream",
          "Kasuri methi (dried fenugreek leaves)",
          "Salt",
        ],
      },
      {
        label: "Garam masala",
        items: [
          "Green cardamom",
          "Black cardamom",
          "Cinnamon",
          "Clove",
          "Black pepper",
          "Cumin",
          "Coriander seed",
          "Bay leaf",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)", "Butter"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 1,
    price: 1190,
    image: generated(
      "/food/dal-makhani-ai.jpg",
      "Dal makhani: dark black lentils in a copper pot with a swirl of cream and a pat of butter, naan and sliced onion beside it",
      { focal: "45% 55%", note: "The naan and onion beside the pot aren't part of this dish." },
    ),
  },
  {
    id: "rogan-josh",
    cuisine: "india",
    name: "Kashmiri Rogan Josh",
    localName: "रोगन जोश",
    tradition: "Kashmiri",
    course: "main",
    story:
      "A Kashmiri lamb braise with a Persian-derived name. Lamb is browned in ghee, then simmered with yogurt, Kashmiri chili, fennel and dried ginger; this Kashmiri Pandit style uses asafoetida in place of onion and garlic.",
    parts: [
      {
        label: "Lamb",
        items: ["Bone-in lamb shoulder", "Yogurt", "Salt"],
      },
      {
        label: "Spices",
        items: [
          "Kashmiri chili (mild, deep-red dried chili)",
          "Fennel seed",
          "Sonth (dried ginger)",
          "Green cardamom",
          "Black cardamom",
          "Clove",
          "Cinnamon",
          "Bay leaf",
          "Asafoetida (pure dried resin, no flour added)",
        ],
      },
      {
        label: "Rogan (colored fat)",
        items: ["Ghee", "Ratan jot (alkanet root, for red color)"],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 2,
    price: 1690,
    image: generated(
      "/food/rogan-josh-ai.jpg",
      "Rogan josh: bone-in lamb pieces in a glossy deep red gravy in a copper pot, rice behind it",
      { focal: "55% 55%", note: "The rice behind the pot isn't part of this dish." },
    ),
  },
  {
    id: "chole-bhature",
    cuisine: "india",
    name: "Chole Bhature",
    localName: "छोले भटूरे",
    tradition: "Punjabi",
    course: "main",
    story:
      "A Punjabi pairing, especially popular in Delhi: chickpeas boiled with black tea for color, then simmered in a tangy onion-tomato masala, served with bhature, a yogurt-leavened bread that puffs when deep-fried.",
    parts: [
      {
        label: "Chole",
        items: [
          "Chickpeas",
          "Black tea (for color)",
          "Onion",
          "Tomato",
          "Ginger",
          "Garlic",
          "Green chili",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Chole masala",
        items: [
          "Coriander seed",
          "Cumin",
          "Anardana (dried pomegranate seed)",
          "Amchur (dried mango powder)",
          "Kashmiri chili (mild, deep-red dried chili)",
          "Black pepper",
          "Black cardamom",
          "Clove",
          "Cinnamon",
          "Bay leaf",
          "Kasuri methi (dried fenugreek leaves)",
        ],
      },
      {
        label: "Bhature",
        items: ["Maida (refined wheat flour)", "Semolina", "Yogurt", "Sugar", "Ghee", "Salt"],
      },
      {
        label: "To serve",
        items: ["Onion", "Green chili", "Lemon"],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk", "wheat"],
    diet: ["vegetarian"],
    spice: 2,
    price: 1250,
    image: generated(
      "/food/chole-bhature-ai.jpg",
      "Chole bhature: a bowl of spiced chickpea curry with two puffed fried breads, sliced onion and a green chili",
    ),
  },
  {
    id: "malai-kofta",
    cuisine: "india",
    name: "Malai Kofta",
    localName: "मलाई कोफ्ता",
    tradition: "Mughlai",
    course: "main",
    story:
      "A North Indian vegetarian dish in the Mughlai style: dumplings of paneer and potato, often stuffed with dried fruit, are fried and served in a smooth, mildly sweet gravy of tomato, onion, cashew and cream.",
    parts: [
      {
        label: "Kofta",
        items: [
          "Paneer (whole milk curdled with lemon juice)",
          "Potato",
          "Cornstarch",
          "Cashew",
          "Raisin",
          "Green chili",
          "Ginger",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Gravy",
        items: [
          "Tomato",
          "Onion",
          "Cashew",
          "Cream",
          "Ginger",
          "Garlic",
          "Green chili",
          "Kashmiri chili (mild, deep-red dried chili)",
          "Kasuri methi (dried fenugreek leaves)",
          "Sugar",
          "Salt",
        ],
      },
      {
        label: "Spices",
        items: [
          "Cumin seed",
          "Coriander seed",
          "Turmeric",
          "Green cardamom",
          "Cinnamon",
          "Clove",
          "Bay leaf",
          "Black pepper",
          "Mace",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk", "tree-nuts"],
    diet: ["vegetarian", "gluten-free"],
    spice: 1,
    price: 1390,
    image: generated(
      "/food/malai-kofta-ai.jpg",
      "Malai kofta: four golden dumplings in a pale orange cream gravy, garnished with cilantro",
      { focal: "45% 50%" },
    ),
  },
  // ─── Nepal ────────────────────────────────────────────────────────────────
  {
    id: "chicken-momo",
    cuisine: "nepal",
    name: "Chicken Momo",
    localName: "चिकेन मोमो",
    course: "small-plate",
    story:
      "Dumplings of Tibetan origin, commonly said to have reached the Kathmandu Valley with Newar merchants trading in Lhasa. Minced chicken seasoned with onion, ginger, garlic and spices is wrapped in thin wheat dough, pleated, steamed and served with tomato-sesame achar (relish).",
    parts: [
      {
        label: "Wrapper",
        items: ["Maida (refined wheat flour)", "Water", "Salt"],
      },
      {
        label: "Filling",
        items: [
          "Minced chicken",
          "Onion",
          "Scallion",
          "Ginger",
          "Garlic",
          "Cilantro",
          "Green chili",
          "Ghee",
          "Salt",
        ],
      },
      {
        label: "Momo masala",
        items: [
          "Cumin",
          "Coriander seed",
          "Turmeric",
          "Timur (Nepali Sichuan pepper)",
          "Black pepper",
          "Cinnamon",
          "Green cardamom",
          "Clove",
          "Nutmeg",
        ],
      },
      {
        label: "Tomato-sesame achar (relish)",
        items: [
          "Tomato",
          "Toasted sesame seed",
          "Dried red chili",
          "Timur",
          "Garlic",
          "Ginger",
          "Cilantro",
          "Lemon juice",
          "Salt",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk", "wheat", "sesame"],
    diet: [],
    spice: 2,
    price: 1290,
    image: generated(
      "/food/chicken-momo-ai.jpg",
      "Chicken momo: pleated steamed dumplings on a plate with a small bowl of orange tomato achar",
    ),
  },
  {
    id: "dal-bhat",
    cuisine: "nepal",
    name: "Dal Bhat Tarkari",
    localName: "दाल भात तरकारी",
    course: "main",
    story:
      "Nepal's everyday meal, eaten twice a day in many households: steamed rice (bhat) with lentil soup (dal) tempered with cumin and jimbu (a Himalayan allium), a vegetable curry (tarkari), sautéed greens and a tomato achar (relish).",
    parts: [
      {
        label: "Dal",
        items: [
          "Rahar dal (split pigeon peas)",
          "Turmeric",
          "Ginger",
          "Jimbu (dried Himalayan allium)",
          "Cumin seed",
          "Garlic",
          "Dried red chili",
          "Salt",
        ],
      },
      {
        label: "Bhat (steamed rice)",
        items: ["Long-grain white rice"],
      },
      {
        label: "Aloo cauli tarkari",
        items: [
          "Potato",
          "Cauliflower",
          "Tomato",
          "Onion",
          "Garlic",
          "Ginger",
          "Green chili",
          "Fenugreek seed",
          "Cumin",
          "Coriander seed",
          "Turmeric",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Rayo saag",
        items: ["Rayo (mustard greens)", "Garlic", "Dried red chili", "Salt"],
      },
      {
        label: "Golbheda achar (tomato relish)",
        items: [
          "Roasted tomato",
          "Garlic",
          "Green chili",
          "Timur (Nepali Sichuan pepper)",
          "Cilantro",
          "Lemon juice",
          "Salt",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["vegetarian", "vegan", "gluten-free"],
    spice: 1,
    price: 1350,
    image: generated(
      "/food/dal-bhat-ai.jpg",
      "Dal bhat tarkari: a brass plate of rice with a bowl of lentil soup, potato curry, greens, tomato achar and a papad",
      { focal: "55% 50%", note: "The papad (crisp lentil wafer) isn't part of our dal bhat." },
    ),
  },
  {
    id: "newari-bara",
    cuisine: "nepal",
    name: "Newari Bara",
    localName: "बारा",
    tradition: "Newar",
    course: "small-plate",
    story:
      "A Newar lentil patty from the Kathmandu Valley, made at festivals and feasts. Soaked black lentils are ground into a thick batter with ginger, garlic and cumin, spread on a hot griddle and often topped with an egg as it cooks.",
    parts: [
      {
        label: "Bara batter",
        items: [
          "Black urad dal (black gram), soaked and ground",
          "Ginger",
          "Garlic",
          "Cumin",
          "Turmeric",
          "Salt",
        ],
      },
      {
        label: "Topping",
        items: ["Egg", "Cilantro"],
      },
      {
        label: "Roasted tomato achar (relish)",
        items: [
          "Fire-roasted tomato",
          "Garlic",
          "Green chili",
          "Timur (Nepali Sichuan pepper)",
          "Cilantro",
          "Salt",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk", "egg"],
    diet: ["vegetarian", "gluten-free"],
    spice: 1,
    price: 1190,
    image: generated(
      "/food/newari-bara-ai.jpg",
      "Newari bara: a dark lentil patty topped with a fried egg, with roasted tomato achar on the side",
      { focal: "45% 50%" },
    ),
  },
  {
    id: "thukpa",
    cuisine: "nepal",
    name: "Thukpa",
    localName: "थुक्पा",
    tradition: "Tibetan",
    course: "noodles",
    story:
      "A noodle soup from Tibetan cooking, eaten across Nepal's mountain regions and in Kathmandu. Hand-cut wheat noodles are served in a chicken broth simmered with ginger, garlic and tomato, with shredded chicken, vegetables, cumin, timur and Himalayan chili.",
    parts: [
      {
        label: "Noodles",
        items: ["Wheat flour", "Water", "Salt"],
      },
      {
        label: "Chicken broth",
        items: [
          "Bone-in chicken",
          "Onion",
          "Garlic",
          "Ginger",
          "Tomato",
          "Soy sauce (soybeans, wheat, salt)",
          "Salt",
        ],
      },
      {
        label: "Vegetables",
        items: ["Cabbage", "Carrot", "Spinach", "Scallion", "Cilantro"],
      },
      {
        label: "Spices",
        items: [
          "Cumin",
          "Coriander seed",
          "Turmeric",
          "Timur (Nepali Sichuan pepper)",
          "Black pepper",
          "Dalle khursani (round Himalayan chili)",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk", "wheat", "soy"],
    diet: [],
    spice: 2,
    price: 1250,
    image: generated(
      "/food/thukpa-ai.jpg",
      "Thukpa: noodles in clear broth with shredded chicken, spinach, carrot, scallion and chili",
    ),
  },
  {
    id: "sel-roti",
    cuisine: "nepal",
    name: "Sel Roti & Aloo Dum",
    localName: "सेल रोटी",
    course: "bread",
    story:
      "A ring-shaped, lightly sweet rice bread made for the Tihar and Dashain festivals: a batter of soaked, ground rice, sugar, ghee and cardamom is poured by hand into hot ghee and fried. Often eaten with aloo dum, potatoes in a spiced gravy.",
    parts: [
      {
        label: "Sel roti",
        items: [
          "Rice (soaked and ground)",
          "Sugar",
          "Milk",
          "Ghee",
          "Ripe banana",
          "Green cardamom",
        ],
      },
      {
        label: "Aloo dum",
        items: [
          "Baby potato",
          "Tomato",
          "Onion",
          "Garlic",
          "Ginger",
          "Green chili",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Aloo dum spices",
        items: [
          "Cumin seed",
          "Coriander seed",
          "Turmeric",
          "Fenugreek seed",
          "Dried red chili",
          "Timur (Nepali Sichuan pepper)",
          "Cinnamon",
          "Clove",
          "Green cardamom",
          "Black pepper",
        ],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 1,
    price: 1090,
    image: generated(
      "/food/sel-roti-ai.jpg",
      "Sel roti and aloo dum: thick golden fried rings beside a brass bowl of spiced potatoes",
      { focal: "40% 55%" },
    ),
  },
  {
    id: "chatamari",
    cuisine: "nepal",
    name: "Chatamari",
    localName: "चटामरी",
    tradition: "Newar",
    course: "small-plate",
    story:
      "A Newar rice crepe from the Kathmandu Valley, made for feasts and festivals. A thin batter of rice flour and water is spread on a hot griddle, topped with spiced minced chicken, egg, tomato and onion, and cooked covered until the top sets.",
    parts: [
      {
        label: "Crepe",
        items: ["Rice flour", "Water", "Salt"],
      },
      {
        label: "Minced chicken",
        items: [
          "Minced chicken",
          "Ginger",
          "Garlic",
          "Green chili",
          "Cumin",
          "Turmeric",
          "Timur (Nepali Sichuan pepper)",
          "Salt",
        ],
      },
      {
        label: "Topping",
        items: ["Egg", "Tomato", "Red onion", "Green chili", "Scallion", "Cilantro"],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk", "egg"],
    diet: ["gluten-free"],
    spice: 1,
    price: 1150,
    image: generated(
      "/food/chatamari-ai.jpg",
      "Chatamari: a thin, round crepe topped with minced meat, a fried egg, tomato, onion, green chili and cilantro",
      { focal: "40% 50%" },
    ),
  },
  {
    id: "chicken-choila",
    cuisine: "nepal",
    name: "Chicken Choila",
    localName: "चोइला",
    tradition: "Newar",
    course: "small-plate",
    story:
      "A Newar dish from the Kathmandu Valley, traditionally made with water buffalo; this version uses chicken. The meat is grilled over an open flame until smoky, cut up, mixed with garlic, ginger, chili and timur, and dressed with hot fat tempered with fenugreek seed.",
    parts: [
      {
        label: "Chicken",
        items: ["Chicken thigh", "Turmeric", "Salt"],
      },
      {
        label: "Choila masala",
        items: [
          "Garlic",
          "Ginger",
          "Green chili",
          "Dried red chili",
          "Timur (Nepali Sichuan pepper)",
          "Cumin",
          "Lemon juice",
          "Scallion",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Tempering",
        items: ["Ghee", "Fenugreek seed", "Dried red chili", "Turmeric"],
      },
      {
        label: "To serve",
        items: ["Chiura (beaten rice)"],
      },
    ],
    cookedIn: ["Ghee (clarified butter)"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 3,
    price: 1450,
    image: generated(
      "/food/chicken-choila-ai.jpg",
      "Chicken choila: flame-charred chicken pieces tossed with spices, scallion and cilantro in a clay bowl",
      { focal: "55% 50%" },
    ),
  },
  {
    id: "yomari",
    cuisine: "nepal",
    name: "Yomari",
    localName: "योमरी",
    tradition: "Newar",
    course: "dessert",
    story:
      "A Newar sweet made for Yomari Punhi, a full-moon festival, usually in December, that follows the rice harvest in the Kathmandu Valley. Rice-flour dough is shaped into a pointed, fish-like pouch, filled with chaku (cane molasses) and toasted sesame, and steamed.",
    parts: [
      {
        label: "Dough",
        items: ["Rice flour", "Hot water"],
      },
      {
        label: "Filling",
        items: ["Chaku (cane molasses)", "Toasted sesame seed"],
      },
    ],
    cookedIn: [],
    allergens: ["sesame"],
    diet: ["vegetarian", "vegan", "gluten-free"],
    spice: 0,
    price: 990,
    image: generated(
      "/food/yomari-ai.jpg",
      "Yomari: five white, teardrop-shaped rice-flour dumplings on a brass plate, one cut open to show a dark sesame filling",
      { focal: "40% 55%" },
    ),
  },
  {
    id: "aloo-tama",
    cuisine: "nepal",
    name: "Aloo Tama",
    localName: "आलु तामा",
    course: "main",
    story:
      "A sour Nepali curry of potatoes, tama (fermented bamboo shoots) and black-eyed peas, simmered with tomato, turmeric and spices tempered with fenugreek seed. The bamboo shoots give the broth its tang; it is usually eaten with rice.",
    parts: [
      {
        label: "Curry",
        items: [
          "Potato",
          "Tama (fermented bamboo shoot)",
          "Bodi (black-eyed peas)",
          "Tomato",
          "Onion",
          "Garlic",
          "Ginger",
          "Green chili",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Spices",
        items: [
          "Fenugreek seed",
          "Cumin seed",
          "Coriander seed",
          "Turmeric",
          "Dried red chili",
          "Timur (Nepali Sichuan pepper)",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["vegetarian", "vegan", "gluten-free"],
    spice: 2,
    price: 1290,
    image: generated(
      "/food/aloo-tama-ai.jpg",
      "Aloo tama: a brass bowl of brothy curry with potato, bamboo shoot strips and black-eyed peas, with rice, greens and pickle on the plate",
      {
        focal: "35% 55%",
        note: "The rice, greens and pickle beside the bowl aren't part of this dish.",
      },
    ),
  },
  {
    id: "gundruk-dhido",
    cuisine: "nepal",
    name: "Gundruk & Dhido",
    localName: "गुन्द्रुक ढिंडो",
    course: "main",
    story:
      "Everyday food of Nepal's hills and mountains. Gundruk, leafy greens fermented and then sun-dried, is simmered into a sour soup with tomato, garlic and timur; dhido is a stiff porridge made by stirring buckwheat flour into boiling water, eaten by hand.",
    parts: [
      {
        label: "Gundruk ko jhol (soup)",
        items: [
          "Gundruk (fermented, sun-dried mustard and radish greens)",
          "Tomato",
          "Onion",
          "Garlic",
          "Ginger",
          "Green chili",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "Spices",
        items: [
          "Cumin seed",
          "Fenugreek seed",
          "Turmeric",
          "Dried red chili",
          "Timur (Nepali Sichuan pepper)",
        ],
      },
      {
        label: "Dhido",
        items: ["Buckwheat flour", "Water", "Salt"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["vegetarian", "vegan", "gluten-free"],
    spice: 1,
    price: 1390,
    image: generated(
      "/food/gundruk-dhido-ai.jpg",
      "Gundruk and dhido: a mound of dark buckwheat dhido beside a bowl of fermented-greens soup and a small bowl of tomato pickle",
      { note: "The small bowl of tomato pickle isn't part of this dish." },
    ),
  },
  // ─── Thailand ─────────────────────────────────────────────────────────────
  {
    id: "pad-thai",
    cuisine: "thailand",
    name: "Pad Thai",
    localName: "ผัดไทย",
    course: "noodles",
    story:
      "Popularized as a national dish under Prime Minister Plaek Phibunsongkhram around the 1940s. Soaked rice noodles are stir-fried with egg, tofu, shrimp and a sauce of tamarind, fish sauce and palm sugar, then finished with bean sprouts, peanuts and lime.",
    parts: [
      {
        label: "Pad Thai sauce",
        items: ["Tamarind pulp", "Fish sauce (anchovy, salt)", "Palm sugar"],
      },
      {
        label: "Stir-fry",
        items: [
          "Dried flat rice noodles (sen chan)",
          "Shrimp",
          "Egg",
          "Firm tofu (soybean curd)",
          "Dried shrimp",
          "Shallot",
          "Garlic",
          "Chai po (salted radish)",
          "Garlic chives",
          "Bean sprouts",
        ],
      },
      {
        label: "To serve",
        items: ["Roasted peanuts", "Dried chili flakes", "Lime", "Raw bean sprouts"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["egg", "soy", "peanuts", "fish", "shellfish"],
    diet: ["gluten-free"],
    spice: 1,
    price: 1390,
    image: representative(
      "/food/pad-thai.jpg",
      "Pad Thai on a white plate: rice noodles with shrimp, scrambled egg and bean sprouts",
      "50% 55%",
    ),
    featured: true,
  },
  {
    id: "green-curry",
    cuisine: "thailand",
    name: "Green Curry",
    localName: "แกงเขียวหวาน",
    tradition: "Central Thai",
    course: "main",
    story:
      "A central Thai curry, kaeng khiao wan in Thai. A paste of fresh green chilies, lemongrass, galangal, makrut lime and shrimp paste is fried in coconut cream, then simmered with coconut milk, chicken, Thai eggplant and Thai basil.",
    parts: [
      {
        label: "Green curry paste",
        items: [
          "Green bird's eye chili",
          "Lemongrass",
          "Galangal (a pungent relative of ginger)",
          "Makrut lime zest (fragrant Southeast Asian lime)",
          "Cilantro root",
          "Shallot",
          "Garlic",
          "Shrimp paste (fermented shrimp, salt)",
          "Coriander seed",
          "Cumin",
          "White pepper",
          "Salt",
        ],
      },
      {
        label: "Curry",
        items: [
          "Chicken thigh",
          "Coconut milk",
          "Coconut cream",
          "Thai eggplant (small, round green eggplant)",
          "Pea eggplant (tiny, slightly bitter eggplant)",
          "Fish sauce (anchovy, salt)",
          "Palm sugar",
          "Makrut lime leaves",
          "Thai basil",
          "Red chili",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["fish", "shellfish"],
    diet: ["gluten-free"],
    spice: 2,
    price: 1450,
    image: generated(
      "/food/green-curry-ai.jpg",
      "Green curry: chicken, round Thai eggplant and pea eggplant in a pale green coconut curry with Thai basil and chili, a bowl of rice beside it",
      { focal: "60% 55%", note: "The bowl of rice isn't part of this dish." },
    ),
  },
  {
    id: "tom-yum",
    cuisine: "thailand",
    name: "Tom Yum Goong",
    localName: "ต้มยำกุ้ง",
    tradition: "Central Thai",
    course: "soup",
    story:
      "A hot and sour soup from central Thailand. Shrimp are simmered in a stock scented with lemongrass, galangal and makrut lime leaves, then seasoned off the heat with fish sauce, lime juice, fresh chilies and nam prik pao (roasted chili paste).",
    parts: [
      {
        label: "Broth",
        items: [
          "Shrimp stock (from shrimp heads and shells)",
          "Lemongrass",
          "Galangal (a pungent relative of ginger)",
          "Makrut lime leaves (fragrant Southeast Asian lime)",
          "Shallot",
          "Cilantro root",
        ],
      },
      {
        label: "Soup",
        items: ["Shrimp", "Straw mushrooms", "Tomato"],
      },
      {
        label: "Seasoning",
        items: [
          "Fish sauce (anchovy, salt)",
          "Lime juice",
          "Bird's eye chili",
          "Nam prik pao (roasted chili paste)",
          "Cilantro",
        ],
      },
      {
        label: "Nam prik pao",
        items: [
          "Dried red chili",
          "Shallot",
          "Garlic",
          "Dried shrimp",
          "Tamarind",
          "Palm sugar",
          "Fish sauce",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["fish", "shellfish"],
    diet: ["gluten-free"],
    spice: 3,
    price: 1290,
    image: generated(
      "/food/tom-yum-ai.jpg",
      "Tom yum goong: red-orange broth with shrimp, mushrooms, lemongrass, galangal, lime leaf, chili and cilantro",
      {
        focal: "40% 55%",
        note: "The mushrooms shown look like button mushrooms; ours are straw mushrooms.",
      },
    ),
  },
  {
    id: "pad-kra-pao",
    cuisine: "thailand",
    name: "Pad Kra Pao",
    localName: "ผัดกะเพรา",
    course: "main",
    story:
      "A Thai street-food staple. Minced chicken is stir-fried over high heat with pounded garlic and bird's eye chilies, seasoned with fish sauce, soy sauce and a little sugar, tossed with holy basil, and served over rice with a crisp fried egg.",
    parts: [
      {
        label: "Stir-fry",
        items: [
          "Minced chicken",
          "Garlic",
          "Bird's eye chili",
          "Holy basil (kra pao, a peppery Thai basil)",
        ],
      },
      {
        label: "Sauce",
        items: [
          "Fish sauce (anchovy, salt)",
          "Light soy sauce (soybeans, wheat, salt)",
          "Palm sugar",
          "Water",
        ],
      },
      {
        label: "To serve",
        items: ["Jasmine rice", "Egg (fried)"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["egg", "wheat", "soy", "fish"],
    diet: [],
    spice: 3,
    price: 1350,
    image: generated(
      "/food/pad-kra-pao-ai.jpg",
      "Pad kra pao: minced meat stir-fried with holy basil and chili, with jasmine rice and a crisp fried egg",
    ),
  },
  {
    id: "massaman",
    cuisine: "thailand",
    name: "Massaman Curry",
    localName: "แกงมัสมั่น",
    tradition: "Thai Muslim",
    course: "main",
    story:
      "A Thai curry associated with Thailand's Muslim communities, its name probably from an old word for Muslim. Thai aromatics are pounded with dry spices such as cardamom, cinnamon and clove, and beef is braised in the paste with coconut milk, potato and peanuts.",
    parts: [
      {
        label: "Massaman paste",
        items: [
          "Dried red chili",
          "Shallot",
          "Garlic",
          "Lemongrass",
          "Galangal (a pungent relative of ginger)",
          "Shrimp paste (fermented shrimp, salt)",
          "Salt",
        ],
      },
      {
        label: "Dry spices",
        items: [
          "Coriander seed",
          "Cumin",
          "Green cardamom",
          "Cinnamon",
          "Clove",
          "Nutmeg",
          "Mace",
          "White pepper",
          "Star anise",
          "Bay leaf",
        ],
      },
      {
        label: "Curry",
        items: [
          "Beef chuck",
          "Coconut milk",
          "Coconut cream",
          "Potato",
          "Onion",
          "Roasted peanuts",
          "Tamarind",
          "Fish sauce (anchovy, salt)",
          "Palm sugar",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["peanuts", "fish", "shellfish"],
    diet: ["gluten-free"],
    spice: 1,
    price: 1550,
    image: generated(
      "/food/massaman-ai.jpg",
      "Massaman curry: beef, potato, shallots and roasted peanuts in a reddish-brown coconut curry, a bowl of rice beside it",
      { focal: "40% 55%", note: "The bowl of rice isn't part of this dish." },
    ),
  },
  {
    id: "som-tam",
    cuisine: "thailand",
    name: "Som Tam",
    localName: "ส้มตำ",
    tradition: "Isan",
    course: "small-plate",
    story:
      "Green papaya salad from Lao and Isan cooking, in its sweeter central Thai form (som tam thai) with dried shrimp and peanuts. Garlic and chili are bruised in a mortar, then papaya, long beans and tomato are pounded with lime, fish sauce and palm sugar.",
    parts: [
      {
        label: "Salad",
        items: [
          "Green papaya",
          "Long bean",
          "Cherry tomato",
          "Dried shrimp",
          "Roasted peanuts",
          "Garlic",
          "Bird's eye chili",
        ],
      },
      {
        label: "Dressing",
        items: ["Lime juice", "Fish sauce (anchovy, salt)", "Palm sugar", "Tamarind"],
      },
    ],
    cookedIn: [],
    allergens: ["peanuts", "fish", "shellfish"],
    diet: ["gluten-free"],
    spice: 3,
    price: 1190,
    image: generated(
      "/food/som-tam-ai.jpg",
      "Som tam: shredded green papaya with long beans, cherry tomatoes, chili, carrot and peanuts, with a lime wedge",
      { focal: "40% 55%", note: "Our som tam has no carrot; the picture shows some." },
    ),
  },
  {
    id: "mango-sticky-rice",
    cuisine: "thailand",
    name: "Mango Sticky Rice",
    localName: "ข้าวเหนียวมะม่วง",
    course: "dessert",
    story:
      "A Thai dessert associated with the hot-season mango harvest. Soaked glutinous rice is steamed, then left to absorb warm coconut milk with sugar and salt, and served with ripe mango, salted coconut cream and toasted mung beans.",
    parts: [
      {
        label: "Sticky rice",
        items: ["Glutinous (sticky) rice", "Coconut milk", "Sugar", "Salt"],
      },
      {
        label: "Coconut topping",
        items: ["Coconut cream", "Rice flour", "Salt"],
      },
      {
        label: "To serve",
        items: ["Ripe mango", "Toasted mung beans"],
      },
    ],
    cookedIn: [],
    allergens: [],
    diet: ["vegetarian", "vegan", "gluten-free"],
    spice: 0,
    price: 890,
    image: generated(
      "/food/mango-sticky-rice-ai.jpg",
      "Mango sticky rice: sliced ripe mango beside a mound of sticky rice with coconut cream and toasted mung beans, on a banana leaf",
    ),
  },
  {
    id: "khao-pad",
    cuisine: "thailand",
    name: "Khao Pad",
    localName: "ข้าวผัด",
    course: "rice",
    story:
      "Thai fried rice of Chinese origin; the crab version is khao pad pu. Day-old jasmine rice is stir-fried with garlic and egg, seasoned with fish sauce and soy sauce, tossed with crab and scallion, and served with cucumber, lime and chili fish sauce.",
    parts: [
      {
        label: "Fried rice",
        items: ["Cooked jasmine rice", "Egg", "Crab meat", "Garlic", "Onion", "Scallion"],
      },
      {
        label: "Seasoning",
        items: [
          "Fish sauce (anchovy, salt)",
          "Light soy sauce (soybeans, wheat, salt)",
          "Sugar",
          "White pepper",
        ],
      },
      {
        label: "To serve",
        items: ["Cucumber", "Lime", "Cilantro", "Prik nam pla (bird's eye chili in fish sauce)"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["egg", "wheat", "soy", "fish", "shellfish"],
    diet: [],
    spice: 1,
    price: 1250,
    // The old photo showed plain fried rice with peas and corn, no crab.
    image: generated(
      "/food/khao-pad-ai.jpg",
      "Khao pad pu: fried rice with egg and crab, cucumber slices, lime and a small bowl of chili fish sauce",
      { focal: "55% 55%" },
    ),
  },
  {
    id: "panang-curry",
    cuisine: "thailand",
    name: "Panang Curry",
    localName: "พะแนง",
    course: "main",
    story:
      "A thick, mildly sweet Thai curry. A dried-chili paste with roasted peanuts, coriander and cumin is fried in coconut cream until the fat separates, then simmered briefly with chicken and finished with finely shredded makrut lime leaves.",
    parts: [
      {
        label: "Panang paste",
        items: [
          "Dried red chili",
          "Shallot",
          "Garlic",
          "Lemongrass",
          "Galangal (a pungent relative of ginger)",
          "Makrut lime zest (fragrant Southeast Asian lime)",
          "Cilantro root",
          "Shrimp paste (fermented shrimp, salt)",
          "Roasted peanuts",
          "Coriander seed",
          "Cumin",
          "White pepper",
          "Salt",
        ],
      },
      {
        label: "Curry",
        items: [
          "Chicken thigh",
          "Coconut cream",
          "Coconut milk",
          "Fish sauce (anchovy, salt)",
          "Palm sugar",
          "Makrut lime leaves",
          "Thai basil",
          "Red chili",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["peanuts", "fish", "shellfish"],
    diet: ["gluten-free"],
    spice: 2,
    price: 1490,
    image: generated(
      "/food/panang-curry-ai.jpg",
      "Panang curry: sliced chicken in a thick red-orange coconut curry with Thai basil, lime leaf and red chili, beside rice",
      { note: "The rice isn't part of this dish." },
    ),
  },
  {
    id: "khao-soi",
    cuisine: "thailand",
    name: "Khao Soi",
    localName: "ข้าวซอย",
    tradition: "Northern Thai",
    course: "noodles",
    story:
      "A curry noodle soup from northern Thailand, especially Chiang Mai, associated with Chinese Muslim (Chin Haw) traders. Egg noodles are served in a coconut curry broth with chicken, topped with crisp fried noodles and eaten with pickled mustard greens, shallot and lime.",
    parts: [
      {
        label: "Khao soi paste",
        items: [
          "Dried red chili",
          "Shallot",
          "Garlic",
          "Ginger",
          "Fresh turmeric",
          "Cilantro root",
          "Salt",
        ],
      },
      {
        label: "Spices",
        items: ["Coriander seed", "Cumin", "Black cardamom", "Fenugreek seed", "Cinnamon", "Clove"],
      },
      {
        label: "Broth",
        items: [
          "Bone-in chicken drumstick",
          "Coconut milk",
          "Coconut cream",
          "Fish sauce (anchovy, salt)",
          "Light soy sauce (soybeans, wheat, salt)",
          "Palm sugar",
        ],
      },
      {
        label: "Noodles and garnish",
        items: [
          "Egg noodles (wheat flour, egg), boiled and crisp-fried",
          "Pickled mustard greens",
          "Shallot",
          "Lime",
          "Cilantro",
          "Toasted dried chili",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["egg", "wheat", "soy", "fish"],
    diet: [],
    spice: 2,
    price: 1450,
    image: generated(
      "/food/khao-soi-ai.jpg",
      "Khao soi: egg noodles and a chicken drumstick in golden curry broth, topped with crisp fried noodles, with lime, shallot and pickled greens",
      { focal: "45% 50%" },
    ),
  },
  // ─── Mexico ───────────────────────────────────────────────────────────────
  {
    id: "tacos-al-pastor",
    cuisine: "mexico",
    name: "Tacos al Pastor",
    localName: "Tacos al pastor",
    tradition: "Mexico City",
    course: "main",
    story:
      "A Mexico City taco adapted from the shawarma brought by Lebanese immigrants. Pork marinated in dried chilies, achiote and pineapple is stacked on a vertical spit (trompo), shaved onto corn tortillas and topped with pineapple, onion and cilantro.",
    parts: [
      {
        label: "Pork",
        items: ["Pork shoulder", "Salt"],
      },
      {
        label: "Adobo (marinade)",
        items: [
          "Guajillo chili (mild dried red chili)",
          "Ancho chili (dried poblano)",
          "Achiote (annatto seed)",
          "Garlic",
          "White onion",
          "Pineapple juice",
          "White vinegar",
          "Mexican oregano",
          "Cumin",
          "Clove",
          "Black pepper",
          "Salt",
        ],
      },
      {
        label: "Corn tortillas",
        items: ["Corn", "Water", "Cal (slaked lime, a mineral used to cook the corn)"],
      },
      {
        label: "Salsa verde",
        items: [
          "Tomatillo (tart green husk tomato)",
          "Serrano chili",
          "White onion",
          "Garlic",
          "Cilantro",
          "Salt",
        ],
      },
      {
        label: "To serve",
        items: ["Roasted pineapple", "White onion", "Cilantro", "Lime"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["gluten-free"],
    spice: 2,
    price: 1390,
    // The old photo showed chickpea-and-avocado tacos, not pork al pastor.
    image: generated(
      "/food/tacos-al-pastor-ai.jpg",
      "Tacos al pastor: three corn tortillas with red marinated pork, pineapple, onion and cilantro, with lime and a red salsa",
      { note: "The salsa shown is red; ours is a green tomatillo salsa." },
    ),
    featured: true,
  },
  {
    id: "mole-poblano",
    cuisine: "mexico",
    name: "Mole Poblano",
    localName: "Mole poblano",
    tradition: "Poblano",
    course: "main",
    story:
      "A festive sauce from Puebla, where legend places its creation in a colonial convent. Dried chilies are toasted and ground with nuts, seeds, spices, tomato, bread and chocolate, then cooked down slowly into a dark sauce served over turkey and sprinkled with sesame.",
    parts: [
      {
        label: "Turkey",
        items: ["Bone-in turkey thigh", "White onion", "Garlic", "Salt"],
      },
      {
        label: "Dried chilies",
        items: [
          "Mulato chili (dark dried poblano)",
          "Ancho chili (dried poblano)",
          "Pasilla chili (dried chilaca chili)",
          "Chipotle chili (smoked dried jalapeño)",
        ],
      },
      {
        label: "Nuts, seeds and fruit",
        items: [
          "Almond",
          "Peanut",
          "Sesame seed",
          "Pepitas (pumpkin seeds)",
          "Raisin",
          "Ripe plantain",
        ],
      },
      {
        label: "Spices",
        items: [
          "Canela (Ceylon cinnamon)",
          "Anise seed",
          "Clove",
          "Black pepper",
          "Coriander seed",
        ],
      },
      {
        label: "Mole base",
        items: [
          "Tomato",
          "Tomatillo (tart green husk tomato)",
          "White onion",
          "Garlic",
          "Stale corn tortilla (corn, water, cal)",
          "Bolillo (bread roll of wheat flour, water, yeast and salt)",
          "Mexican chocolate (cacao, sugar, cinnamon)",
          "Sugar",
          "Turkey broth",
          "Salt",
          "Toasted sesame seed (to finish)",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["wheat", "peanuts", "tree-nuts", "sesame"],
    diet: [],
    spice: 1,
    price: 1650,
    image: generated(
      "/food/mole-poblano-ai.jpg",
      "Mole poblano: pieces of poultry covered in dark mole and sesame seeds, beside red rice",
      {
        focal: "55% 55%",
        note: "The red rice isn't part of this dish, and ours is made with bone-in turkey thigh.",
      },
    ),
  },
  {
    id: "carne-asada",
    cuisine: "mexico",
    name: "Carne Asada Plate",
    localName: "Carne asada",
    tradition: "Norteño",
    course: "main",
    story:
      "Beef grilled over wood or charcoal, a tradition strongest in northern Mexico, where mesquite is the classic fuel. Skirt steak marinated in citrus and garlic is grilled over high heat, sliced, and served with salsa roja, beans, red rice and corn tortillas.",
    parts: [
      {
        label: "Steak",
        items: [
          "Skirt steak",
          "Orange juice",
          "Lime juice",
          "Garlic",
          "Cilantro",
          "Cumin",
          "Black pepper",
          "Salt",
        ],
      },
      {
        label: "Salsa roja",
        items: [
          "Roasted tomato",
          "Chile de árbol (small, hot dried chili)",
          "Garlic",
          "White onion",
          "Salt",
        ],
      },
      {
        label: "Beans and red rice",
        items: [
          "Pinto beans",
          "Long-grain rice",
          "Tomato",
          "White onion",
          "Garlic",
          "Chicken broth",
          "Salt",
        ],
      },
      {
        label: "Corn tortillas",
        items: ["Corn", "Water", "Cal (slaked lime, a mineral used to cook the corn)"],
      },
      {
        label: "To serve",
        items: ["Grilled cebollitas (spring onions)", "Lime", "Cilantro"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["gluten-free"],
    spice: 1,
    price: 1590,
    image: generated(
      "/food/carne-asada-ai.jpg",
      "Carne asada plate: sliced grilled steak with red rice, beans topped with crumbled cheese, salsa roja, grilled spring onions, lime and corn tortillas",
      { note: "Our beans aren't topped with cheese." },
    ),
  },
  {
    id: "enchiladas-verdes",
    cuisine: "mexico",
    name: "Enchiladas Verdes",
    localName: "Enchiladas verdes",
    course: "main",
    story:
      "The name comes from enchilar, to season with chili. Corn tortillas are briefly fried to soften them, rolled around shredded chicken and covered with a salsa verde of tomatillos and serrano chilies, then finished with crema, queso fresco and raw onion.",
    parts: [
      {
        label: "Chicken",
        items: ["Chicken breast", "White onion", "Garlic", "Bay leaf", "Salt"],
      },
      {
        label: "Salsa verde",
        items: [
          "Tomatillo (tart green husk tomato)",
          "Serrano chili",
          "White onion",
          "Garlic",
          "Cilantro",
          "Chicken broth",
          "Salt",
        ],
      },
      {
        label: "Tortillas",
        items: ["Corn", "Water", "Cal (slaked lime, a mineral used to cook the corn)"],
      },
      {
        label: "Toppings",
        items: [
          "Mexican crema (cultured cream)",
          "Queso fresco (fresh cheese)",
          "White onion",
          "Cilantro",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 1,
    price: 1350,
    image: generated(
      "/food/enchiladas-verdes-ai.jpg",
      "Enchiladas verdes: rolled tortillas filled with chicken under green tomatillo salsa, crema, crumbled cheese, onion and cilantro",
    ),
  },
  {
    id: "chiles-rellenos",
    cuisine: "mexico",
    name: "Chiles Rellenos",
    localName: "Chiles rellenos",
    course: "main",
    story:
      "Stuffed chilies made across Mexico, most often with poblanos, which take their name from Puebla. The chilies are charred, peeled, stuffed with cheese, dusted with flour, coated in whipped-egg batter (capeado) and fried, then served in a light tomato broth (caldillo).",
    parts: [
      {
        label: "Stuffed chilies",
        items: ["Poblano chili", "Queso Oaxaca (stretched-curd cheese)"],
      },
      {
        label: "Capeado (egg batter)",
        items: ["Egg", "Wheat flour (for dusting)", "Salt"],
      },
      {
        label: "Caldillo (tomato broth)",
        items: ["Tomato", "White onion", "Garlic", "Mexican oregano", "Bay leaf", "Water", "Salt"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk", "egg", "wheat"],
    diet: ["vegetarian"],
    spice: 1,
    price: 1450,
    image: generated(
      "/food/chiles-rellenos-ai.jpg",
      "Chiles rellenos: two batter-fried poblano chilies in tomato broth, with rice on the plate",
      { focal: "40% 55%", note: "The rice isn't part of this dish." },
    ),
  },
  {
    id: "pozole-rojo",
    cuisine: "mexico",
    name: "Pozole Rojo",
    localName: "Pozole rojo",
    tradition: "Jaliscan",
    course: "soup",
    story:
      "A hominy stew with pre-Hispanic roots; the red version is associated with Jalisco. Pork is simmered with hominy (lime-treated corn) until the kernels burst open, the broth is reddened with guajillo and ancho chilies, and it is served with cabbage, radish, oregano and lime.",
    parts: [
      {
        label: "Stew",
        items: [
          "Pork shoulder",
          "Pork neck bones",
          "Hominy (corn kernels cooked with slaked lime)",
          "White onion",
          "Garlic",
          "Bay leaf",
          "Salt",
        ],
      },
      {
        label: "Chili purée",
        items: [
          "Guajillo chili (mild dried red chili)",
          "Ancho chili (dried poblano)",
          "Garlic",
          "White onion",
          "Mexican oregano",
          "Cumin",
          "Salt",
        ],
      },
      {
        label: "Garnishes",
        items: [
          "Shredded cabbage",
          "Radish",
          "White onion",
          "Dried Mexican oregano",
          "Ground chile de árbol (small, hot dried chili)",
          "Lime",
          "Tostadas (fried tortillas of corn, water and cal)",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: [],
    diet: ["gluten-free"],
    spice: 2,
    price: 1390,
    image: generated(
      "/food/pozole-rojo-ai.jpg",
      "Pozole rojo: red chili broth with pork and hominy, topped with shredded cabbage, radish and oregano",
      { focal: "45% 55%" },
    ),
  },
  {
    id: "tamales",
    cuisine: "mexico",
    name: "Tamales Oaxaqueños",
    localName: "Tamales oaxaqueños",
    tradition: "Oaxacan",
    course: "main",
    story:
      "Oaxaca's tamales de mole negro are wrapped in banana leaves rather than corn husks, giving a soft, moist masa (corn dough). The beaten masa is spread on a leaf, filled with shredded chicken and mole negro, folded into a flat parcel and steamed.",
    parts: [
      {
        label: "Masa and wrapper",
        items: [
          "Corn",
          "Water",
          "Cal (slaked lime, a mineral used to cook the corn)",
          "Butter",
          "Chicken broth",
          "Salt",
          "Banana leaf",
        ],
      },
      {
        label: "Filling",
        items: ["Chicken", "White onion", "Garlic", "Salt"],
      },
      {
        label: "Mole negro chilies",
        items: [
          "Chilhuacle negro (dried black chili)",
          "Mulato chili (dark dried poblano)",
          "Pasilla chili (dried chilaca chili)",
          "Chipotle chili (smoked dried jalapeño)",
        ],
      },
      {
        label: "Mole negro base",
        items: [
          "Mexican chocolate (cacao, sugar, cinnamon)",
          "Almond",
          "Peanut",
          "Sesame seed",
          "Raisin",
          "Ripe plantain",
          "Tomato",
          "Tomatillo (tart green husk tomato)",
          "White onion",
          "Garlic",
          "Charred corn tortilla (corn, water, cal)",
          "Bolillo (bread roll of wheat flour, water, yeast and salt)",
          "Avocado leaf",
          "Salt",
        ],
      },
      {
        label: "Mole spices",
        items: [
          "Canela (Ceylon cinnamon)",
          "Clove",
          "Black pepper",
          "Allspice",
          "Cumin",
          "Mexican oregano",
          "Thyme",
          "Marjoram",
        ],
      },
    ],
    cookedIn: ["Olive oil", "Butter"],
    allergens: ["milk", "wheat", "peanuts", "tree-nuts", "sesame"],
    diet: [],
    spice: 1,
    price: 1290,
    image: generated(
      "/food/tamales-ai.jpg",
      "Tamales oaxaqueños: a tamal unwrapped on banana leaves, showing masa with shredded chicken and dark mole negro",
      { focal: "55% 55%" },
    ),
  },
  {
    id: "huitlacoche-quesadilla",
    cuisine: "mexico",
    name: "Huitlacoche Quesadilla",
    localName: "Quesadilla de huitlacoche",
    tradition: "Central Mexican",
    course: "small-plate",
    story:
      "Huitlacoche, a fungus that grows on corn during the rainy season, has been eaten in central Mexico since pre-Hispanic times. It is sautéed with onion, garlic and epazote, then folded into a blue-corn tortilla with Oaxaca cheese and cooked on a comal (griddle).",
    parts: [
      {
        label: "Filling",
        items: [
          "Huitlacoche (corn mushroom)",
          "White onion",
          "Garlic",
          "Epazote (pungent Mexican herb)",
          "Queso Oaxaca (stretched-curd cheese)",
          "Salt",
        ],
      },
      {
        label: "Blue-corn tortilla",
        items: ["Blue corn", "Water", "Cal (slaked lime, a mineral used to cook the corn)"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 0,
    price: 1350,
    image: generated(
      "/food/huitlacoche-quesadilla-ai.jpg",
      "Huitlacoche quesadilla: a folded blue-corn tortilla with dark huitlacoche and melted cheese, with a bowl of green salsa",
      { focal: "40% 55%", note: "The bowl of green salsa isn't part of this dish." },
    ),
  },
  {
    id: "chilaquiles",
    cuisine: "mexico",
    name: "Chilaquiles",
    localName: "Chilaquiles",
    course: "main",
    story:
      "A Mexican breakfast of leftover tortillas; the name comes from Nahuatl. Tortilla wedges are fried until crisp, simmered briefly in salsa verde until just softened, and topped with crema, queso fresco, raw onion and a fried egg.",
    parts: [
      {
        label: "Totopos (fried tortilla wedges)",
        items: ["Corn", "Water", "Cal (slaked lime, a mineral used to cook the corn)", "Salt"],
      },
      {
        label: "Salsa verde",
        items: [
          "Tomatillo (tart green husk tomato)",
          "Serrano chili",
          "White onion",
          "Garlic",
          "Cilantro",
          "Epazote (pungent Mexican herb)",
          "Salt",
        ],
      },
      {
        label: "Toppings",
        items: [
          "Egg (fried)",
          "Mexican crema (cultured cream)",
          "Queso fresco (fresh cheese)",
          "White onion",
          "Cilantro",
          "Avocado",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk", "egg"],
    diet: ["vegetarian", "gluten-free"],
    spice: 2,
    price: 1250,
    image: generated(
      "/food/chilaquiles-ai.jpg",
      "Chilaquiles: tortilla chips in green salsa topped with a fried egg, crema, crumbled cheese, onion and cilantro",
    ),
  },
  {
    id: "elote-guacamole",
    cuisine: "mexico",
    name: "Elote & Guacamole",
    localName: "Elote y guacamole",
    course: "small-plate",
    story:
      "Two Mexican classics: elote, corn grilled on the cob and coated with crema, crumbled cotija and chili, sold by street vendors; and guacamole, avocado mashed in a molcajete (stone mortar) with onion, chili, cilantro and lime, a preparation going back to the Aztecs.",
    parts: [
      {
        label: "Elote",
        items: [
          "Sweet corn on the cob",
          "Butter",
          "Mexican crema (cultured cream)",
          "Cotija (aged, crumbly cow's milk cheese)",
          "Ground chile de árbol (small, hot dried chili)",
          "Lime",
          "Salt",
        ],
      },
      {
        label: "Guacamole",
        items: [
          "Hass avocado",
          "White onion",
          "Serrano chili",
          "Cilantro",
          "Tomato",
          "Lime juice",
          "Salt",
        ],
      },
      {
        label: "Totopos (tortilla chips)",
        items: ["Corn", "Water", "Cal (slaked lime, a mineral used to cook the corn)", "Salt"],
      },
    ],
    cookedIn: ["Butter", "Olive oil"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 1,
    price: 990,
    image: generated(
      "/food/elote-guacamole-ai.jpg",
      "Elote and guacamole: grilled corn on the cob with crema, cotija and chili, beside a bowl of chunky guacamole and lime wedges",
      { focal: "45% 55%" },
    ),
  },
  // ─── Italy ────────────────────────────────────────────────────────────────
  {
    id: "margherita",
    cuisine: "italy",
    name: "Margherita",
    localName: "Pizza Margherita",
    tradition: "Neapolitan",
    course: "main",
    story:
      "A Neapolitan pizza whose red, white and green toppings echo the Italian flag; tradition ties its name to Queen Margherita's 1889 visit to Naples. Hand-stretched dough is topped with tomato, mozzarella, basil and olive oil and baked quickly in a very hot oven.",
    parts: [
      {
        label: "Dough",
        items: ["Tipo 00 wheat flour (finely milled)", "Water", "Yeast", "Salt"],
      },
      {
        label: "Toppings",
        items: [
          "Peeled plum tomatoes, crushed",
          "Fior di latte (cow's milk mozzarella)",
          "Basil",
          "Extra-virgin olive oil",
          "Salt",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk", "wheat"],
    diet: ["vegetarian"],
    spice: 0,
    price: 1490,
    image: representative(
      "/food/margherita.jpg",
      "Margherita pizza with a blistered crust, tomato, melted mozzarella and basil leaves on a marble table",
      "50% 50%",
    ),
    featured: true,
  },
  {
    id: "carbonara",
    cuisine: "italy",
    name: "Carbonara",
    localName: "Spaghetti alla carbonara",
    tradition: "Roman",
    course: "main",
    story:
      "A Roman pasta first documented in the mid-20th century. Guanciale (cured pork jowl) is crisped in its own fat, then tossed off the heat with hot spaghetti, egg yolks, Pecorino Romano and black pepper, which emulsify into a creamy sauce without cream.",
    parts: [
      {
        label: "Pasta",
        items: ["Spaghetti (durum wheat semolina, water)", "Salt (for the cooking water)"],
      },
      {
        label: "Guanciale (cured pork jowl)",
        items: ["Pork jowl", "Salt", "Black pepper"],
      },
      {
        label: "Sauce",
        items: [
          "Egg yolk",
          "Whole egg",
          "Pecorino Romano (aged sheep's milk cheese made with animal rennet)",
          "Black pepper",
        ],
      },
    ],
    cookedIn: [],
    allergens: ["milk", "egg", "wheat"],
    diet: [],
    spice: 0,
    price: 1550,
    image: representative(
      "/food/carbonara.jpg",
      "Spaghetti carbonara in a white bowl, topped with crisp diced cured pork and grated cheese",
      "50% 45%",
    ),
  },
  {
    id: "lasagna",
    cuisine: "italy",
    name: "Lasagna Bolognese",
    localName: "Lasagne alla bolognese",
    tradition: "Bolognese",
    course: "main",
    story:
      "The baked lasagne of Bologna, traditionally made with green spinach-egg pasta. Sheets of egg pasta are layered with béchamel, Parmigiano Reggiano and ragù alla bolognese, a slow-cooked sauce of minced beef and pork, then baked until the edges crisp.",
    parts: [
      {
        label: "Pasta",
        items: ["Tipo 00 wheat flour (finely milled)", "Egg", "Spinach"],
      },
      {
        label: "Ragù alla bolognese",
        items: [
          "Minced beef",
          "Minced pork",
          "Pancetta (cured pork belly)",
          "Onion",
          "Carrot",
          "Celery",
          "Tomato",
          "Dry white wine",
          "Whole milk",
          "Butter",
          "Salt",
          "Black pepper",
        ],
      },
      {
        label: "Béchamel",
        items: ["Whole milk", "Butter", "Wheat flour", "Nutmeg", "Salt"],
      },
      {
        label: "To finish",
        items: ["Parmigiano Reggiano (aged cow's milk cheese made with animal rennet)", "Butter"],
      },
    ],
    cookedIn: ["Butter", "Olive oil"],
    allergens: ["milk", "egg", "wheat"],
    diet: [],
    spice: 0,
    price: 1650,
    image: representative(
      "/food/lasagna.jpg",
      "A square of baked lasagna with a browned cheese top on tomato sauce, garnished with crisp cured ham, cherry tomatoes and herbs",
      "50% 50%",
      "The ham garnish isn't in our recipe, and our pasta is green (spinach).",
    ),
  },
  {
    id: "cacio-e-pepe",
    cuisine: "italy",
    name: "Cacio e Pepe",
    localName: "Cacio e pepe",
    tradition: "Roman",
    course: "main",
    story:
      "A Roman pasta named for its two seasonings, cheese and pepper, with roots in the food of Lazio's shepherds. Tonnarelli are tossed with finely grated Pecorino Romano, toasted black pepper and starchy pasta water until they form a smooth, creamy sauce.",
    parts: [
      {
        label: "Tonnarelli (fresh egg pasta)",
        items: ["Durum wheat semolina", "Egg", "Salt (for the cooking water)"],
      },
      {
        label: "Sauce",
        items: [
          "Pecorino Romano (aged sheep's milk cheese made with animal rennet)",
          "Black pepper, toasted and cracked",
          "Starchy pasta water",
        ],
      },
    ],
    cookedIn: [],
    allergens: ["milk", "egg", "wheat"],
    diet: ["vegetarian"],
    spice: 1,
    price: 1450,
    image: generated(
      "/food/cacio-e-pepe-ai.jpg",
      "Cacio e pepe: long pasta coated in creamy pecorino sauce with coarse black pepper",
      { focal: "45% 55%" },
    ),
  },
  {
    id: "osso-buco",
    cuisine: "italy",
    name: "Osso Buco",
    localName: "Ossobuco alla milanese",
    tradition: "Milanese",
    course: "main",
    story:
      "A Milanese braise whose name means bone with a hole, after the marrow-filled shank bone. Cross-cut veal shanks are floured, browned in butter, braised with white wine, broth and aromatics, finished with gremolata, and served with saffron risotto.",
    parts: [
      {
        label: "Veal",
        items: [
          "Veal shank, cross-cut",
          "Wheat flour (for dusting)",
          "Onion",
          "Carrot",
          "Celery",
          "Dry white wine",
          "Beef broth",
          "Butter",
          "Salt",
          "Black pepper",
        ],
      },
      {
        label: "Gremolata",
        items: ["Lemon zest", "Garlic", "Flat-leaf parsley"],
      },
      {
        label: "Risotto alla milanese",
        items: [
          "Carnaroli rice (short-grain risotto rice)",
          "Saffron",
          "Beef broth",
          "Onion",
          "Dry white wine",
          "Butter",
          "Parmigiano Reggiano (aged cow's milk cheese made with animal rennet)",
          "Salt",
        ],
      },
    ],
    cookedIn: ["Butter"],
    allergens: ["milk", "wheat"],
    diet: [],
    spice: 0,
    price: 1890,
    image: generated(
      "/food/osso-buco-ai.jpg",
      "Osso buco: a braised cross-cut veal shank with its marrow bone, topped with gremolata, beside golden saffron risotto",
    ),
  },
  {
    id: "risotto-milanese",
    cuisine: "italy",
    name: "Risotto alla Milanese",
    localName: "Risotto alla milanese",
    tradition: "Milanese",
    course: "rice",
    story:
      "Milan's saffron risotto, linked by legend to the glaziers of Milan Cathedral in 1574. Carnaroli rice is toasted in butter with onion and beef marrow, cooked with wine and broth added gradually, colored with saffron and finished with butter and Parmigiano.",
    parts: [
      {
        label: "Risotto",
        items: [
          "Carnaroli rice (short-grain risotto rice)",
          "Onion",
          "Beef bone marrow",
          "Dry white wine",
          "Saffron",
          "Butter",
          "Salt",
        ],
      },
      {
        label: "Beef broth",
        items: ["Beef", "Beef bones", "Onion", "Carrot", "Celery", "Salt"],
      },
      {
        label: "Mantecatura (to finish)",
        items: ["Butter", "Parmigiano Reggiano (aged cow's milk cheese made with animal rennet)"],
      },
    ],
    cookedIn: ["Butter"],
    allergens: ["milk"],
    diet: ["gluten-free"],
    spice: 0,
    price: 1690,
    image: generated(
      "/food/risotto-milanese-ai.jpg",
      "Risotto alla milanese: golden saffron risotto with grated Parmigiano and saffron threads",
      { focal: "55% 55%" },
    ),
  },
  {
    id: "gnocchi-pesto",
    cuisine: "italy",
    name: "Gnocchi al Pesto",
    localName: "Gnocchi al pesto",
    tradition: "Ligurian",
    course: "main",
    story:
      "Pesto alla genovese, from Genoa in Liguria, is a raw sauce of basil, pine nuts, garlic, Parmigiano, pecorino and olive oil, traditionally pounded in a marble mortar. It is tossed with soft potato gnocchi and green beans.",
    parts: [
      {
        label: "Gnocchi",
        items: ["Floury potato", "Tipo 00 wheat flour (finely milled)", "Salt"],
      },
      {
        label: "Pesto alla genovese",
        items: [
          "Basil",
          "Pine nuts",
          "Garlic",
          "Coarse sea salt",
          "Parmigiano Reggiano (aged cow's milk cheese made with animal rennet)",
          "Pecorino Sardo (aged sheep's milk cheese made with animal rennet)",
          "Extra-virgin olive oil",
        ],
      },
      {
        label: "Vegetables",
        items: ["Green beans", "Salt"],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk", "wheat", "tree-nuts"],
    diet: ["vegetarian"],
    spice: 0,
    price: 1490,
    image: generated(
      "/food/gnocchi-pesto-ai.jpg",
      "Gnocchi al pesto: potato gnocchi in bright green basil pesto with green beans, pine nuts and grated cheese",
      { focal: "45% 55%" },
    ),
  },
  {
    id: "eggplant-parmigiana",
    cuisine: "italy",
    name: "Eggplant Parmigiana",
    localName: "Parmigiana di melanzane",
    tradition: "Southern Italian",
    course: "main",
    story:
      "A southern Italian dish claimed by both Campania and Sicily. Eggplant slices are salted, fried and layered with tomato sauce, basil, mozzarella and Parmigiano, then baked; it is often served warm rather than hot.",
    parts: [
      {
        label: "Eggplant",
        items: ["Eggplant", "Salt"],
      },
      {
        label: "Tomato sauce",
        items: [
          "Tomato passata (strained tomato purée)",
          "Garlic",
          "Basil",
          "Extra-virgin olive oil",
          "Salt",
        ],
      },
      {
        label: "Layers",
        items: [
          "Fior di latte mozzarella",
          "Parmigiano Reggiano (aged cow's milk cheese made with animal rennet)",
          "Basil",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 0,
    price: 1390,
    image: generated(
      "/food/eggplant-parmigiana-ai.jpg",
      "Eggplant parmigiana: a baked square of layered eggplant, tomato sauce and melted mozzarella, topped with basil",
    ),
  },
  {
    id: "tiramisu",
    cuisine: "italy",
    name: "Tiramisu",
    localName: "Tiramisù",
    tradition: "Venetian",
    course: "dessert",
    story:
      "A dessert from northeast Italy, popularized in Treviso in the Veneto from the late 1960s; Friuli also claims it. Espresso-soaked ladyfingers are layered with a cream of egg yolks, sugar and mascarpone, dusted with cocoa and chilled.",
    parts: [
      {
        label: "Savoiardi (ladyfingers)",
        items: ["Egg", "Sugar", "Wheat flour"],
      },
      {
        label: "Mascarpone cream",
        items: ["Mascarpone (cream set with citric acid)", "Egg yolk (uncooked)", "Sugar"],
      },
      {
        label: "Soak and finish",
        items: ["Espresso", "Unsweetened cocoa powder"],
      },
    ],
    cookedIn: [],
    allergens: ["milk", "egg", "wheat"],
    diet: ["vegetarian"],
    spice: 0,
    price: 890,
    image: representative(
      "/food/tiramisu.jpg",
      "A square of layered tiramisu dusted with cocoa, topped with pomegranate seeds and a small decorative plaque, on a patterned plate",
      "50% 65%",
      "The pomegranate garnish isn't in our recipe.",
    ),
  },
  {
    id: "burrata-caprese",
    cuisine: "italy",
    name: "Burrata Caprese",
    localName: "Caprese con burrata",
    course: "small-plate",
    story:
      "Insalata caprese is named for the island of Capri. This version swaps mozzarella for burrata, a fresh cheese from Puglia: a pouch of mozzarella filled with stracciatella (shreds of curd in cream), served with tomato, basil and olive oil.",
    parts: [
      {
        label: "Burrata",
        items: [
          "Mozzarella shell (cow's milk curd)",
          "Stracciatella (shreds of mozzarella curd in cream)",
          "Salt",
        ],
      },
      {
        label: "Salad",
        items: [
          "Ripe tomatoes",
          "Basil",
          "Extra-virgin olive oil",
          "Flaky sea salt",
          "Black pepper",
        ],
      },
    ],
    cookedIn: ["Olive oil"],
    allergens: ["milk"],
    diet: ["vegetarian", "gluten-free"],
    spice: 0,
    price: 1250,
    image: generated(
      "/food/burrata-caprese-ai.jpg",
      "Burrata caprese: a whole burrata over sliced ripe tomatoes with basil, olive oil, salt and pepper",
      { focal: "55% 55%" },
    ),
  },
];
