import type { Recipe } from "./types.ts";

/**
 * Guided home recipes, keyed by dish id. Each one cooks the same dish the
 * menu describes: every ingredient maps to an item in that dish's parts list,
 * and `npm run test:menu` fails if one is missing or invented.
 *
 * Status is recorded per recipe. A recipe stays "draft" until someone has
 * cooked it from these instructions and signed it off (`checkedBy`, `checkedOn`).
 */
export const recipes: Record<string, Recipe> = {
  "chicken-momo": {
    dishId: "chicken-momo",
    servings: 4,
    yields: { amount: 30, noun: "momos" },
    time: { active: 75, total: 105 },
    difficulty: "Takes practice",
    equipment: [
      "Steamer with a lid (bamboo or metal)",
      "Rolling pin",
      "Spice grinder, or mortar and pestle",
      "Blender",
      "Heavy dry pan",
      "Instant-read thermometer (recommended)",
    ],
    content: {
      status: "draft",
      source:
        "Written for WorldFoodCuisine from this dish's ingredient list with AI assistance (Claude), September 2026. Not yet test-cooked.",
    },
    ingredients: [
      // Wrapper
      {
        id: "flour",
        item: "Maida (refined wheat flour)",
        part: "Wrapper",
        label: "Maida (all-purpose flour)",
        metric: { amount: 300, unit: "g" },
        us: { amount: 2.5, unit: "cup" },
        prep: "spooned and leveled",
        aisle: "pantry",
        allergens: ["wheat"],
        substitutes: [
          {
            name: "All-purpose flour",
            note: "The same thing: maida is refined wheat flour.",
          },
          {
            name: "Gluten-free flour blend with xanthan gum",
            note: "Untested. The dough tears more easily: roll it a little thicker and fold half-moons instead of pleats.",
            removes: ["wheat"],
          },
        ],
      },
      {
        id: "water",
        item: "Water",
        part: "Wrapper",
        metric: { amount: 165, unit: "ml" },
        us: { amount: 0.67, unit: "cup" },
        prep: "lukewarm",
        aisle: "pantry",
      },
      {
        id: "salt-dough",
        item: "Salt",
        part: "Wrapper",
        metric: { amount: 0.5, unit: "tsp" },
        aisle: "pantry",
      },
      // Momo masala
      {
        id: "cumin",
        item: "Cumin",
        part: "Momo masala",
        label: "Cumin seeds",
        metric: { amount: 0.5, unit: "tsp" },
        aisle: "spices",
      },
      {
        id: "coriander",
        item: "Coriander seed",
        part: "Momo masala",
        label: "Coriander seeds",
        metric: { amount: 0.5, unit: "tsp" },
        aisle: "spices",
      },
      {
        id: "timur-masala",
        item: "Timur (Nepali Sichuan pepper)",
        part: "Momo masala",
        label: "Timur (Nepali Sichuan pepper)",
        metric: { amount: 0.25, unit: "tsp" },
        aisle: "spices",
        substitutes: [
          {
            name: "Sichuan peppercorns",
            note: "The closest match. Timur is more citrusy; Sichuan pepper is more floral.",
          },
        ],
      },
      {
        id: "pepper",
        item: "Black pepper",
        part: "Momo masala",
        label: "Black peppercorns",
        metric: { amount: 0.25, unit: "tsp" },
        aisle: "spices",
      },
      {
        id: "cinnamon",
        item: "Cinnamon",
        part: "Momo masala",
        label: "Cinnamon stick",
        metric: { amount: 1, unit: "piece" },
        prep: "2 cm (¾ in) piece",
        aisle: "spices",
      },
      {
        id: "cardamom",
        item: "Green cardamom",
        part: "Momo masala",
        label: "Green cardamom pods",
        metric: { amount: 2, unit: "piece" },
        aisle: "spices",
      },
      {
        id: "clove",
        item: "Clove",
        part: "Momo masala",
        label: "Whole cloves",
        metric: { amount: 2, unit: "piece" },
        aisle: "spices",
      },
      {
        id: "nutmeg",
        item: "Nutmeg",
        part: "Momo masala",
        label: "Nutmeg, freshly grated",
        metric: { amount: 1, unit: "pinch" },
        aisle: "spices",
      },
      {
        id: "turmeric",
        item: "Turmeric",
        part: "Momo masala",
        label: "Ground turmeric",
        metric: { amount: 0.25, unit: "tsp" },
        aisle: "spices",
      },
      // Filling
      {
        id: "chicken",
        item: "Minced chicken",
        part: "Filling",
        label: "Minced chicken, preferably thigh",
        metric: { amount: 450, unit: "g" },
        us: { amount: 1, unit: "lb" },
        aisle: "meat",
        substitutes: [
          {
            name: "Minced turkey",
            note: "Leaner: add 1 tbsp more ghee so the filling stays juicy.",
          },
          {
            name: "Mushrooms and cabbage, finely chopped",
            aisle: "produce",
            amount: "Same weight in total, salted for 10 minutes and squeezed dry",
            note: "Makes a different dish: vegetable momo. Squeeze out the water or the wrappers go soggy.",
          },
        ],
      },
      {
        id: "onion",
        item: "Onion",
        part: "Filling",
        metric: { amount: 1, unit: "piece" },
        prep: "medium, finely chopped (about 150 g)",
        aisle: "produce",
      },
      {
        id: "scallion",
        item: "Scallion",
        part: "Filling",
        label: "Scallions",
        metric: { amount: 4, unit: "piece" },
        prep: "thinly sliced",
        aisle: "produce",
      },
      {
        id: "ginger-filling",
        item: "Ginger",
        part: "Filling",
        label: "Fresh ginger",
        metric: { amount: 1, unit: "tbsp" },
        prep: "finely grated",
        aisle: "produce",
      },
      {
        id: "garlic-filling",
        item: "Garlic",
        part: "Filling",
        metric: { amount: 4, unit: "clove" },
        prep: "finely grated",
        aisle: "produce",
      },
      {
        id: "cilantro-filling",
        item: "Cilantro",
        part: "Filling",
        metric: { amount: 15, unit: "g" },
        us: { amount: 0.5, unit: "cup" },
        prep: "chopped, leaves and tender stems",
        aisle: "produce",
        substitutes: [
          {
            name: "More scallion",
            note: "For anyone who finds cilantro soapy. Less fresh and green.",
          },
        ],
      },
      {
        id: "chili-filling",
        item: "Green chili",
        part: "Filling",
        label: "Green chilies",
        metric: { amount: 2, unit: "piece" },
        prep: "finely chopped; 1 for a milder filling",
        aisle: "produce",
        substitutes: [
          {
            name: "Leave them out",
            note: "A mild filling. The achar still brings the heat.",
          },
        ],
      },
      {
        id: "ghee",
        item: "Ghee",
        part: "Filling",
        label: "Ghee, melted",
        metric: { amount: 2, unit: "tbsp" },
        aisle: "dairy",
        allergens: ["milk"],
        substitutes: [
          {
            name: "Unsalted butter, melted",
            note: "Same allergen (milk). Slightly sweeter and less nutty.",
          },
          {
            name: "Olive oil",
            note: "Dairy-free. A lighter, less rich filling.",
            aisle: "pantry",
            removes: ["milk"],
          },
        ],
      },
      {
        id: "salt-filling",
        item: "Salt",
        part: "Filling",
        metric: { amount: 1, unit: "tsp" },
        aisle: "pantry",
      },
      {
        id: "ghee-tray",
        item: "Ghee",
        part: "Filling",
        label: "Ghee, for the steamer",
        metric: { amount: 1, unit: "tsp" },
        aisle: "dairy",
        allergens: ["milk"],
        substitutes: [
          {
            name: "Olive oil",
            note: "Dairy-free. Works just as well.",
            aisle: "pantry",
            removes: ["milk"],
          },
        ],
      },
      // Tomato-sesame achar
      {
        id: "tomato",
        item: "Tomato",
        part: "Tomato-sesame achar (relish)",
        label: "Ripe tomatoes",
        metric: { amount: 3, unit: "piece" },
        prep: "medium (about 400 g)",
        aisle: "produce",
      },
      {
        id: "sesame",
        item: "Toasted sesame seed",
        part: "Tomato-sesame achar (relish)",
        label: "Sesame seeds",
        metric: { amount: 3, unit: "tbsp" },
        prep: "you'll toast them",
        aisle: "pantry",
        allergens: ["sesame"],
        substitutes: [
          {
            name: "Pumpkin seeds (pepitas)",
            aisle: "pantry",
            note: "Nuttier, and the achar turns greener. Check the packet for sesame cross-contact.",
            removes: ["sesame"],
          },
        ],
      },
      {
        id: "dried-chili",
        item: "Dried red chili",
        part: "Tomato-sesame achar (relish)",
        label: "Dried red chilies",
        metric: { amount: 3, unit: "piece" },
        prep: "stems removed; 1 or 2 for milder",
        aisle: "spices",
        substitutes: [
          {
            name: "Kashmiri chilies",
            note: "Deep red color with much less heat.",
          },
        ],
      },
      {
        id: "timur-achar",
        item: "Timur",
        part: "Tomato-sesame achar (relish)",
        label: "Timur (Nepali Sichuan pepper)",
        metric: { amount: 0.25, unit: "tsp" },
        aisle: "spices",
        substitutes: [
          {
            name: "Sichuan peppercorns",
            note: "The closest match. Timur is more citrusy; Sichuan pepper is more floral.",
          },
        ],
      },
      {
        id: "garlic-achar",
        item: "Garlic",
        part: "Tomato-sesame achar (relish)",
        metric: { amount: 3, unit: "clove" },
        aisle: "produce",
      },
      {
        id: "ginger-achar",
        item: "Ginger",
        part: "Tomato-sesame achar (relish)",
        label: "Fresh ginger",
        metric: { amount: 1, unit: "tsp" },
        prep: "grated",
        aisle: "produce",
      },
      {
        id: "cilantro-achar",
        item: "Cilantro",
        part: "Tomato-sesame achar (relish)",
        metric: { amount: 10, unit: "g" },
        us: { amount: 0.33, unit: "cup" },
        prep: "a small handful",
        aisle: "produce",
      },
      {
        id: "lemon",
        item: "Lemon juice",
        part: "Tomato-sesame achar (relish)",
        metric: { amount: 1, unit: "tbsp" },
        aisle: "produce",
        substitutes: [{ name: "Lime juice", note: "Works the same." }],
      },
      {
        id: "salt-achar",
        item: "Salt",
        part: "Tomato-sesame achar (relish)",
        metric: { amount: 0.75, unit: "tsp" },
        aisle: "pantry",
      },
    ],
    steps: [
      {
        id: "dough",
        section: "Dough",
        title: "Make the dough",
        uses: ["flour", "salt-dough", "water"],
        text: "Mix {flour} with {salt-dough} in a large bowl. Pour in {water} a little at a time, stirring, until a shaggy dough forms. Knead on the counter for 8 to 10 minutes until smooth, firm and springy. Add a spoonful more water only if it won't come together. Cover with a damp towel.",
        timer: { seconds: 1800, label: "Dough rest" },
        tip: "Start the rest timer and keep going: the masala, filling and achar all fit inside these 30 minutes.",
      },
      {
        id: "toast-spices",
        section: "Masala",
        title: "Toast the whole spices",
        uses: ["cumin", "coriander", "timur-masala", "pepper", "cinnamon", "cardamom", "clove"],
        text: "Put {cumin}, {coriander}, {timur-masala}, {pepper}, {cinnamon}, {cardamom} and {clove} in a dry pan over medium heat. Stir for 1 to 2 minutes, until fragrant and a shade darker, then tip onto a plate to cool.",
        timer: { seconds: 120, label: "Toast spices" },
        caution: "Spices go from toasted to burnt in seconds. If they smoke, start again.",
      },
      {
        id: "grind",
        section: "Masala",
        title: "Grind the momo masala",
        uses: ["nutmeg", "turmeric"],
        text: "Grind the cooled spices to a fine powder in a spice grinder or mortar and pestle. Stir in {nutmeg} and {turmeric}. This is your momo masala.",
      },
      {
        id: "chop",
        section: "Filling",
        title: "Chop the aromatics",
        uses: [
          "onion",
          "scallion",
          "ginger-filling",
          "garlic-filling",
          "cilantro-filling",
          "chili-filling",
        ],
        text: "Finely chop {onion}. Slice {scallion}. Grate {ginger-filling} and {garlic-filling}. Chop {cilantro-filling} and {chili-filling}. Keep everything small: big pieces tear the wrappers.",
      },
      {
        id: "mix-filling",
        section: "Filling",
        title: "Mix the filling",
        uses: ["chicken", "ghee", "salt-filling"],
        text: "Combine {chicken}, the chopped aromatics, all of the momo masala, {salt-filling} and {ghee} (slightly cooled). Mix with your hand or a spoon for 1 to 2 minutes, until sticky and even. Cover and refrigerate while you make the achar.",
        caution:
          "Raw chicken: wash your hands, board and knife in hot soapy water before touching anything else.",
      },
      {
        id: "char-tomatoes",
        section: "Achar",
        title: "Char the tomatoes",
        uses: ["tomato"],
        text: "Put {tomato} whole in a dry heavy pan over medium-high heat. Turn them every few minutes until the skins blister and blacken in spots and the tomatoes soften, 8 to 10 minutes.",
        timer: { seconds: 600, label: "Char tomatoes" },
        tip: "No heavy pan? Simmer them in boiling water for 5 minutes instead. You'll lose some smokiness.",
      },
      {
        id: "toast-sesame",
        section: "Achar",
        title: "Toast the sesame and chilies",
        uses: ["sesame", "dried-chili"],
        text: "In the same dry pan over medium-low heat, stir {sesame} for 2 to 3 minutes until golden and nutty. Add {dried-chili} for the last 30 seconds.",
        timer: { seconds: 180, label: "Toast sesame" },
        caution: "Sesame burns fast. Keep stirring, and take it off the heat as soon as it's golden.",
      },
      {
        id: "blend-achar",
        section: "Achar",
        title: "Blend the achar",
        uses: ["timur-achar", "garlic-achar", "ginger-achar", "cilantro-achar", "lemon", "salt-achar"],
        text: "Blend the tomatoes (skins and all), sesame and chilies with {timur-achar}, {garlic-achar}, {ginger-achar}, {cilantro-achar}, {lemon} and {salt-achar} until smooth and pourable. Taste, and add salt or lemon until it's bright and a little tingly.",
      },
      {
        id: "divide",
        section: "Shape",
        title: "Divide the dough",
        text: "Knead the rested dough for 30 seconds, roll it into a log and cut it into {yield} equal pieces, about 15 g each. Keep them under the towel so they don't dry out.",
      },
      {
        id: "roll",
        section: "Shape",
        title: "Roll the wrappers",
        text: "Flatten a piece and roll it into a circle about 8 to 9 cm (3½ in) across, thinner at the edge than in the middle, so the pleats don't turn thick and doughy. Roll a few at a time and keep them covered.",
      },
      {
        id: "fill",
        section: "Shape",
        title: "Fill and pleat",
        text: "Put a heaped tablespoon of filling (about 20 g) in the center. Pleat the edge all the way around, pressing each fold against the last, then pinch the top closed. Easier: fold it into a half-moon and press the edge flat. Set finished momos on a floured tray, covered.",
        tip: "Leave a little room at the top. Overfilled momos burst in the steamer.",
      },
      {
        id: "steam-setup",
        section: "Steam",
        title: "Heat the steamer",
        uses: ["ghee-tray"],
        text: "Bring 5 cm (2 in) of water to a boil under your steamer. Brush the trays with {ghee-tray} and set the momos about 2 cm (¾ in) apart so they don't stick together.",
      },
      {
        id: "steam",
        section: "Steam",
        title: "Steam the momos",
        text: "Cover and steam over high heat for 10 to 12 minutes, until the wrappers look slightly translucent and the filling feels firm.",
        timer: { seconds: 720, label: "Steam momos" },
        caution:
          "Cut one open to check: no pink, and clear juices. Chicken is safe at 74°C (165°F) on a thermometer.",
      },
      {
        id: "serve",
        section: "Serve",
        title: "Serve hot",
        text: "Serve straight from the steamer with the achar for dipping. Steam the next batch while you eat the first.",
        tip: "Uncooked momos freeze well on a tray. Steam them from frozen for about 15 minutes.",
      },
    ],
  },
};

export function recipeFor(dishId: string): Recipe | undefined {
  return recipes[dishId];
}
